backend:
  name: test-repo

media_folder: static/assets

collections:
  - name: "cv"
    label: "Resume"
    folder: "src/markdown-pages"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Resume", widget: "markdown" }
